contentmunch:
  auth:
    accessTokenMaxAgeInMinutes: 30
    refreshTokenMaxAgeDays: 7
    secret: contentmunchcontentmunchcontentmunch!
    cookie:
      name: contentmunch
      same-site: STRICT
      secure: true
      http-only: true
      path: /
      refresh-token-path: /api/auth/refresh
    users:
      contentmunch:
        name: Contentmunch
        username: contentmunch
        email: mail@contentmunch.com
        password: "{noop}password"
        roles: ROLE_USER,ROLE_ADMIN
  logging:
    enabled: true
  telemetry:
    enabled: true
otel:
  logs:
    exporter: none
  metrics:
    exporter: none
  traces:
    exporter: none
