contentmunch:
  logging:
    enabled: true
  telemetry:
    enabled: true
otel:
  logs:
    exporter: none
  metrics:
    exporter: none
  traces:
    exporter: none

spring:
  profiles:
    #    use- loki-logging for logging to loki, or use text-logging
    active: text-logging

logging:
  loki:
    url: http://loki.contentmunch.com
    app-name: ${spring.application.name:unknown-app}
    environment: prod
    username: loki
    password: loki-Palto

